package com.order.mapper;

import com.simpleShop.pojo.MqMessageConsumer;
import com.simpleShop.pojo.MqMessageConsumerExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MqMessageConsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_consumer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int countByExample(MqMessageConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_consumer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int deleteByExample(MqMessageConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_consumer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int insert(MqMessageConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_consumer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int insertSelective(MqMessageConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_consumer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    List<MqMessageConsumer> selectByExample(MqMessageConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_consumer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") MqMessageConsumer record, @Param("example") MqMessageConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_consumer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int updateByExample(@Param("record") MqMessageConsumer record, @Param("example") MqMessageConsumerExample example);
}