package com.simpleShop.mapper;

import com.simpleShop.pojo.GoodsOrderLog;
import com.simpleShop.pojo.GoodsOrderLogExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface GoodsOrderLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int countByExample(GoodsOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int deleteByExample(GoodsOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int insert(GoodsOrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int insertSelective(GoodsOrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    List<GoodsOrderLog> selectByExample(GoodsOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") GoodsOrderLog record, @Param("example") GoodsOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int updateByExample(@Param("record") GoodsOrderLog record, @Param("example") GoodsOrderLogExample example);
}