package com.simpleShop.mapper;

import com.simpleShop.pojo.MqMessageProducer;
import com.simpleShop.pojo.MqMessageProducerExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MqMessageProducerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_producer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int countByExample(MqMessageProducerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_producer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int deleteByExample(MqMessageProducerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_producer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_producer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int insert(MqMessageProducer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_producer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int insertSelective(MqMessageProducer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_producer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    List<MqMessageProducer> selectByExample(MqMessageProducerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_producer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    MqMessageProducer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_producer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") MqMessageProducer record, @Param("example") MqMessageProducerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_producer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int updateByExample(@Param("record") MqMessageProducer record, @Param("example") MqMessageProducerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_producer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int updateByPrimaryKeySelective(MqMessageProducer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mq_message_producer
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int updateByPrimaryKey(MqMessageProducer record);
}