package com.simpleShop.mapper;

import com.simpleShop.pojo.OrderPay;
import com.simpleShop.pojo.OrderPayExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrderPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int countByExample(OrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int deleteByExample(OrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int insert(OrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int insertSelective(OrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    List<OrderPay> selectByExample(OrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") OrderPay record, @Param("example") OrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int updateByExample(@Param("record") OrderPay record, @Param("example") OrderPayExample example);
}