package com.user.mapper;

import com.simpleShop.pojo.UserAmountLog;
import com.simpleShop.pojo.UserAmountLogExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserAmountLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_amount_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int countByExample(UserAmountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_amount_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int deleteByExample(UserAmountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_amount_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int insert(UserAmountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_amount_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int insertSelective(UserAmountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_amount_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    List<UserAmountLog> selectByExample(UserAmountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_amount_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserAmountLog record, @Param("example") UserAmountLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_amount_log
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    int updateByExample(@Param("record") UserAmountLog record, @Param("example") UserAmountLogExample example);
}