package com.simpleShop.pojo;

import java.util.Date;

public class GoodsOrderLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order_log.goods_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order_log.order_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order_log.goods_number
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Integer goodsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order_log.log_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Date logTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order_log.goods_id
     *
     * @return the value of goods_order_log.goods_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order_log.goods_id
     *
     * @param goodsId the value for goods_order_log.goods_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order_log.order_id
     *
     * @return the value of goods_order_log.order_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order_log.order_id
     *
     * @param orderId the value for goods_order_log.order_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order_log.goods_number
     *
     * @return the value of goods_order_log.goods_number
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order_log.goods_number
     *
     * @param goodsNumber the value for goods_order_log.goods_number
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order_log.log_time
     *
     * @return the value of goods_order_log.log_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order_log.log_time
     *
     * @param logTime the value for goods_order_log.log_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }
}