package com.simpleShop.pojo;

import java.util.Date;

public class MqMessageProducer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_message_producer.id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_message_producer.group_name
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_message_producer.msg_topic
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private String msgTopic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_message_producer.msg_tag
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private String msgTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_message_producer.msg_key
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private String msgKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_message_producer.msg_body
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private String msgBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_message_producer.msg_status
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Integer msgStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_message_producer.create_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_message_producer.id
     *
     * @return the value of mq_message_producer.id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_message_producer.id
     *
     * @param id the value for mq_message_producer.id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_message_producer.group_name
     *
     * @return the value of mq_message_producer.group_name
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_message_producer.group_name
     *
     * @param groupName the value for mq_message_producer.group_name
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_message_producer.msg_topic
     *
     * @return the value of mq_message_producer.msg_topic
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public String getMsgTopic() {
        return msgTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_message_producer.msg_topic
     *
     * @param msgTopic the value for mq_message_producer.msg_topic
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setMsgTopic(String msgTopic) {
        this.msgTopic = msgTopic == null ? null : msgTopic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_message_producer.msg_tag
     *
     * @return the value of mq_message_producer.msg_tag
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public String getMsgTag() {
        return msgTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_message_producer.msg_tag
     *
     * @param msgTag the value for mq_message_producer.msg_tag
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setMsgTag(String msgTag) {
        this.msgTag = msgTag == null ? null : msgTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_message_producer.msg_key
     *
     * @return the value of mq_message_producer.msg_key
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public String getMsgKey() {
        return msgKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_message_producer.msg_key
     *
     * @param msgKey the value for mq_message_producer.msg_key
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setMsgKey(String msgKey) {
        this.msgKey = msgKey == null ? null : msgKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_message_producer.msg_body
     *
     * @return the value of mq_message_producer.msg_body
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public String getMsgBody() {
        return msgBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_message_producer.msg_body
     *
     * @param msgBody the value for mq_message_producer.msg_body
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setMsgBody(String msgBody) {
        this.msgBody = msgBody == null ? null : msgBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_message_producer.msg_status
     *
     * @return the value of mq_message_producer.msg_status
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Integer getMsgStatus() {
        return msgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_message_producer.msg_status
     *
     * @param msgStatus the value for mq_message_producer.msg_status
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setMsgStatus(Integer msgStatus) {
        this.msgStatus = msgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_message_producer.create_time
     *
     * @return the value of mq_message_producer.create_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_message_producer.create_time
     *
     * @param createTime the value for mq_message_producer.create_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}