package com.simpleShop.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_status
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_status
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.shipping_status
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Integer shippingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.address
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.consignee
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_number
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Integer goodsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_price
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_amount
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private BigDecimal goodsAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.shipping_fee
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private BigDecimal shippingFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_amount
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.coupon_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Long couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.coupon_paid
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private BigDecimal couponPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.money_paid
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private BigDecimal moneyPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_amount
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private BigDecimal payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.add_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.confirm_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Date confirmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Date payTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_status
     *
     * @return the value of order.order_status
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_status
     *
     * @param orderStatus the value for order.order_status
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_status
     *
     * @return the value of order.pay_status
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_status
     *
     * @param payStatus the value for order.pay_status
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.shipping_status
     *
     * @return the value of order.shipping_status
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Integer getShippingStatus() {
        return shippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.shipping_status
     *
     * @param shippingStatus the value for order.shipping_status
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setShippingStatus(Integer shippingStatus) {
        this.shippingStatus = shippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.address
     *
     * @return the value of order.address
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.address
     *
     * @param address the value for order.address
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.consignee
     *
     * @return the value of order.consignee
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.consignee
     *
     * @param consignee the value for order.consignee
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_id
     *
     * @return the value of order.goods_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_id
     *
     * @param goodsId the value for order.goods_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_number
     *
     * @return the value of order.goods_number
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_number
     *
     * @param goodsNumber the value for order.goods_number
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_price
     *
     * @return the value of order.goods_price
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_price
     *
     * @param goodsPrice the value for order.goods_price
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_amount
     *
     * @return the value of order.goods_amount
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public BigDecimal getGoodsAmount() {
        return goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_amount
     *
     * @param goodsAmount the value for order.goods_amount
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setGoodsAmount(BigDecimal goodsAmount) {
        this.goodsAmount = goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.shipping_fee
     *
     * @return the value of order.shipping_fee
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public BigDecimal getShippingFee() {
        return shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.shipping_fee
     *
     * @param shippingFee the value for order.shipping_fee
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setShippingFee(BigDecimal shippingFee) {
        this.shippingFee = shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_amount
     *
     * @return the value of order.order_amount
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_amount
     *
     * @param orderAmount the value for order.order_amount
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.coupon_id
     *
     * @return the value of order.coupon_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.coupon_id
     *
     * @param couponId the value for order.coupon_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.coupon_paid
     *
     * @return the value of order.coupon_paid
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public BigDecimal getCouponPaid() {
        return couponPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.coupon_paid
     *
     * @param couponPaid the value for order.coupon_paid
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setCouponPaid(BigDecimal couponPaid) {
        this.couponPaid = couponPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.money_paid
     *
     * @return the value of order.money_paid
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public BigDecimal getMoneyPaid() {
        return moneyPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.money_paid
     *
     * @param moneyPaid the value for order.money_paid
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setMoneyPaid(BigDecimal moneyPaid) {
        this.moneyPaid = moneyPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_amount
     *
     * @return the value of order.pay_amount
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_amount
     *
     * @param payAmount the value for order.pay_amount
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.add_time
     *
     * @return the value of order.add_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.add_time
     *
     * @param addTime the value for order.add_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.confirm_time
     *
     * @return the value of order.confirm_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Date getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.confirm_time
     *
     * @param confirmTime the value for order.confirm_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setConfirmTime(Date confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_time
     *
     * @return the value of order.pay_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_time
     *
     * @param payTime the value for order.pay_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }
}