package com.simpleShop.pojo;

import java.math.BigDecimal;

public class OrderPay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Long payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.order_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.pay_amount
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private BigDecimal payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_pay.is_paid
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Integer isPaid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_id
     *
     * @return the value of order_pay.pay_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_id
     *
     * @param payId the value for order_pay.pay_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.order_id
     *
     * @return the value of order_pay.order_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.order_id
     *
     * @param orderId the value for order_pay.order_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.pay_amount
     *
     * @return the value of order_pay.pay_amount
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.pay_amount
     *
     * @param payAmount the value for order_pay.pay_amount
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_pay.is_paid
     *
     * @return the value of order_pay.is_paid
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Integer getIsPaid() {
        return isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_pay.is_paid
     *
     * @param isPaid the value for order_pay.is_paid
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setIsPaid(Integer isPaid) {
        this.isPaid = isPaid;
    }
}