package com.simpleShop.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_password
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_mobile
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_score
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Integer userScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_reg_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Date userRegTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_money
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private BigDecimal userMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_mobile
     *
     * @return the value of user.user_mobile
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_mobile
     *
     * @param userMobile the value for user.user_mobile
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_score
     *
     * @return the value of user.user_score
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Integer getUserScore() {
        return userScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_score
     *
     * @param userScore the value for user.user_score
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setUserScore(Integer userScore) {
        this.userScore = userScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_reg_time
     *
     * @return the value of user.user_reg_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Date getUserRegTime() {
        return userRegTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_reg_time
     *
     * @param userRegTime the value for user.user_reg_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setUserRegTime(Date userRegTime) {
        this.userRegTime = userRegTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_money
     *
     * @return the value of user.user_money
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public BigDecimal getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_money
     *
     * @param userMoney the value for user.user_money
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setUserMoney(BigDecimal userMoney) {
        this.userMoney = userMoney;
    }
}