package com.simpleShop.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class UserAmountLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_amount_log.user_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_amount_log.order_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_amount_log.money_log_type
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Integer moneyLogType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_amount_log.use_money
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private BigDecimal useMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_amount_log.create_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_amount_log.user_id
     *
     * @return the value of user_amount_log.user_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_amount_log.user_id
     *
     * @param userId the value for user_amount_log.user_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_amount_log.order_id
     *
     * @return the value of user_amount_log.order_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_amount_log.order_id
     *
     * @param orderId the value for user_amount_log.order_id
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_amount_log.money_log_type
     *
     * @return the value of user_amount_log.money_log_type
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Integer getMoneyLogType() {
        return moneyLogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_amount_log.money_log_type
     *
     * @param moneyLogType the value for user_amount_log.money_log_type
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setMoneyLogType(Integer moneyLogType) {
        this.moneyLogType = moneyLogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_amount_log.use_money
     *
     * @return the value of user_amount_log.use_money
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public BigDecimal getUseMoney() {
        return useMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_amount_log.use_money
     *
     * @param useMoney the value for user_amount_log.use_money
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setUseMoney(BigDecimal useMoney) {
        this.useMoney = useMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_amount_log.create_time
     *
     * @return the value of user_amount_log.create_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_amount_log.create_time
     *
     * @param createTime the value for user_amount_log.create_time
     *
     * @mbggenerated Sun May 02 21:10:59 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}